/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSendRouteImport } from './routes/_authenticated/send'
import { Route as AuthenticatedMembersRouteImport } from './routes/_authenticated/members'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedGroupsRouteImport } from './routes/_authenticated/groups'
import { Route as AuthenticatedDevicesRouteImport } from './routes/_authenticated/devices'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedCampaignsRouteImport } from './routes/_authenticated/campaigns'
import { Route as AuthenticatedBrandsRouteImport } from './routes/_authenticated/brands'
import { Route as AuthenticatedBlockedRouteImport } from './routes/_authenticated/blocked'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as ApiPublicPluginSendRouteImport } from './routes/api/public/plugin/send'
import { Route as ApiPublicPluginSelectDeviceRouteImport } from './routes/api/public/plugin/select-device'
import { Route as ApiPublicPluginHeartbeatRouteImport } from './routes/api/public/plugin/heartbeat'
import { Route as ApiPublicPluginDevicesRouteImport } from './routes/api/public/plugin/devices'
import { Route as ApiPublicPluginActivateRouteImport } from './routes/api/public/plugin/activate'
import { Route as ApiPublicCronTickRouteImport } from './routes/api/public/cron/tick'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSendRoute = AuthenticatedSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMembersRoute = AuthenticatedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroupsRoute = AuthenticatedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevicesRoute = AuthenticatedDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCampaignsRoute = AuthenticatedCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBrandsRoute = AuthenticatedBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBlockedRoute = AuthenticatedBlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicPluginSendRoute = ApiPublicPluginSendRouteImport.update({
  id: '/api/public/plugin/send',
  path: '/api/public/plugin/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPluginSelectDeviceRoute =
  ApiPublicPluginSelectDeviceRouteImport.update({
    id: '/api/public/plugin/select-device',
    path: '/api/public/plugin/select-device',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPluginHeartbeatRoute =
  ApiPublicPluginHeartbeatRouteImport.update({
    id: '/api/public/plugin/heartbeat',
    path: '/api/public/plugin/heartbeat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPluginDevicesRoute = ApiPublicPluginDevicesRouteImport.update({
  id: '/api/public/plugin/devices',
  path: '/api/public/plugin/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPluginActivateRoute = ApiPublicPluginActivateRouteImport.update({
  id: '/api/public/plugin/activate',
  path: '/api/public/plugin/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronTickRoute = ApiPublicCronTickRouteImport.update({
  id: '/api/public/cron/tick',
  path: '/api/public/cron/tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/blocked': typeof AuthenticatedBlockedRoute
  '/brands': typeof AuthenticatedBrandsRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/devices': typeof AuthenticatedDevicesRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/members': typeof AuthenticatedMembersRoute
  '/send': typeof AuthenticatedSendRoute
  '/users': typeof AuthenticatedUsersRoute
  '/api/public/cron/tick': typeof ApiPublicCronTickRoute
  '/api/public/plugin/activate': typeof ApiPublicPluginActivateRoute
  '/api/public/plugin/devices': typeof ApiPublicPluginDevicesRoute
  '/api/public/plugin/heartbeat': typeof ApiPublicPluginHeartbeatRoute
  '/api/public/plugin/select-device': typeof ApiPublicPluginSelectDeviceRoute
  '/api/public/plugin/send': typeof ApiPublicPluginSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/blocked': typeof AuthenticatedBlockedRoute
  '/brands': typeof AuthenticatedBrandsRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/devices': typeof AuthenticatedDevicesRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/members': typeof AuthenticatedMembersRoute
  '/send': typeof AuthenticatedSendRoute
  '/users': typeof AuthenticatedUsersRoute
  '/api/public/cron/tick': typeof ApiPublicCronTickRoute
  '/api/public/plugin/activate': typeof ApiPublicPluginActivateRoute
  '/api/public/plugin/devices': typeof ApiPublicPluginDevicesRoute
  '/api/public/plugin/heartbeat': typeof ApiPublicPluginHeartbeatRoute
  '/api/public/plugin/select-device': typeof ApiPublicPluginSelectDeviceRoute
  '/api/public/plugin/send': typeof ApiPublicPluginSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/blocked': typeof AuthenticatedBlockedRoute
  '/_authenticated/brands': typeof AuthenticatedBrandsRoute
  '/_authenticated/campaigns': typeof AuthenticatedCampaignsRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/devices': typeof AuthenticatedDevicesRoute
  '/_authenticated/groups': typeof AuthenticatedGroupsRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/members': typeof AuthenticatedMembersRoute
  '/_authenticated/send': typeof AuthenticatedSendRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/api/public/cron/tick': typeof ApiPublicCronTickRoute
  '/api/public/plugin/activate': typeof ApiPublicPluginActivateRoute
  '/api/public/plugin/devices': typeof ApiPublicPluginDevicesRoute
  '/api/public/plugin/heartbeat': typeof ApiPublicPluginHeartbeatRoute
  '/api/public/plugin/select-device': typeof ApiPublicPluginSelectDeviceRoute
  '/api/public/plugin/send': typeof ApiPublicPluginSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/activity'
    | '/blocked'
    | '/brands'
    | '/campaigns'
    | '/contacts'
    | '/dashboard'
    | '/devices'
    | '/groups'
    | '/logs'
    | '/members'
    | '/send'
    | '/users'
    | '/api/public/cron/tick'
    | '/api/public/plugin/activate'
    | '/api/public/plugin/devices'
    | '/api/public/plugin/heartbeat'
    | '/api/public/plugin/select-device'
    | '/api/public/plugin/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/activity'
    | '/blocked'
    | '/brands'
    | '/campaigns'
    | '/contacts'
    | '/dashboard'
    | '/devices'
    | '/groups'
    | '/logs'
    | '/members'
    | '/send'
    | '/users'
    | '/api/public/cron/tick'
    | '/api/public/plugin/activate'
    | '/api/public/plugin/devices'
    | '/api/public/plugin/heartbeat'
    | '/api/public/plugin/select-device'
    | '/api/public/plugin/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/activity'
    | '/_authenticated/blocked'
    | '/_authenticated/brands'
    | '/_authenticated/campaigns'
    | '/_authenticated/contacts'
    | '/_authenticated/dashboard'
    | '/_authenticated/devices'
    | '/_authenticated/groups'
    | '/_authenticated/logs'
    | '/_authenticated/members'
    | '/_authenticated/send'
    | '/_authenticated/users'
    | '/api/public/cron/tick'
    | '/api/public/plugin/activate'
    | '/api/public/plugin/devices'
    | '/api/public/plugin/heartbeat'
    | '/api/public/plugin/select-device'
    | '/api/public/plugin/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicCronTickRoute: typeof ApiPublicCronTickRoute
  ApiPublicPluginActivateRoute: typeof ApiPublicPluginActivateRoute
  ApiPublicPluginDevicesRoute: typeof ApiPublicPluginDevicesRoute
  ApiPublicPluginHeartbeatRoute: typeof ApiPublicPluginHeartbeatRoute
  ApiPublicPluginSelectDeviceRoute: typeof ApiPublicPluginSelectDeviceRoute
  ApiPublicPluginSendRoute: typeof ApiPublicPluginSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/send': {
      id: '/_authenticated/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof AuthenticatedSendRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members': {
      id: '/_authenticated/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthenticatedMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups': {
      id: '/_authenticated/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devices': {
      id: '/_authenticated/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AuthenticatedDevicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns': {
      id: '/_authenticated/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthenticatedCampaignsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brands': {
      id: '/_authenticated/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof AuthenticatedBrandsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/blocked': {
      id: '/_authenticated/blocked'
      path: '/blocked'
      fullPath: '/blocked'
      preLoaderRoute: typeof AuthenticatedBlockedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/plugin/send': {
      id: '/api/public/plugin/send'
      path: '/api/public/plugin/send'
      fullPath: '/api/public/plugin/send'
      preLoaderRoute: typeof ApiPublicPluginSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/plugin/select-device': {
      id: '/api/public/plugin/select-device'
      path: '/api/public/plugin/select-device'
      fullPath: '/api/public/plugin/select-device'
      preLoaderRoute: typeof ApiPublicPluginSelectDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/plugin/heartbeat': {
      id: '/api/public/plugin/heartbeat'
      path: '/api/public/plugin/heartbeat'
      fullPath: '/api/public/plugin/heartbeat'
      preLoaderRoute: typeof ApiPublicPluginHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/plugin/devices': {
      id: '/api/public/plugin/devices'
      path: '/api/public/plugin/devices'
      fullPath: '/api/public/plugin/devices'
      preLoaderRoute: typeof ApiPublicPluginDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/plugin/activate': {
      id: '/api/public/plugin/activate'
      path: '/api/public/plugin/activate'
      fullPath: '/api/public/plugin/activate'
      preLoaderRoute: typeof ApiPublicPluginActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/tick': {
      id: '/api/public/cron/tick'
      path: '/api/public/cron/tick'
      fullPath: '/api/public/cron/tick'
      preLoaderRoute: typeof ApiPublicCronTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedBlockedRoute: typeof AuthenticatedBlockedRoute
  AuthenticatedBrandsRoute: typeof AuthenticatedBrandsRoute
  AuthenticatedCampaignsRoute: typeof AuthenticatedCampaignsRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDevicesRoute: typeof AuthenticatedDevicesRoute
  AuthenticatedGroupsRoute: typeof AuthenticatedGroupsRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedMembersRoute: typeof AuthenticatedMembersRoute
  AuthenticatedSendRoute: typeof AuthenticatedSendRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedBlockedRoute: AuthenticatedBlockedRoute,
  AuthenticatedBrandsRoute: AuthenticatedBrandsRoute,
  AuthenticatedCampaignsRoute: AuthenticatedCampaignsRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDevicesRoute: AuthenticatedDevicesRoute,
  AuthenticatedGroupsRoute: AuthenticatedGroupsRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedMembersRoute: AuthenticatedMembersRoute,
  AuthenticatedSendRoute: AuthenticatedSendRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicCronTickRoute: ApiPublicCronTickRoute,
  ApiPublicPluginActivateRoute: ApiPublicPluginActivateRoute,
  ApiPublicPluginDevicesRoute: ApiPublicPluginDevicesRoute,
  ApiPublicPluginHeartbeatRoute: ApiPublicPluginHeartbeatRoute,
  ApiPublicPluginSelectDeviceRoute: ApiPublicPluginSelectDeviceRoute,
  ApiPublicPluginSendRoute: ApiPublicPluginSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
