/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrderRouteImport } from './routes/order'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSendRouteImport } from './routes/_authenticated/send'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedMembersRouteImport } from './routes/_authenticated/members'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedLicensesRouteImport } from './routes/_authenticated/licenses'
import { Route as AuthenticatedGroupsRouteImport } from './routes/_authenticated/groups'
import { Route as AuthenticatedDevicesRouteImport } from './routes/_authenticated/devices'
import { Route as AuthenticatedDeviceRequestsRouteImport } from './routes/_authenticated/device-requests'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedCampaignsRouteImport } from './routes/_authenticated/campaigns'
import { Route as AuthenticatedBrandsRouteImport } from './routes/_authenticated/brands'
import { Route as AuthenticatedBlockedRouteImport } from './routes/_authenticated/blocked'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as ApiPublicWhmcsUpdateRouteImport } from './routes/api/public/whmcs/update'
import { Route as ApiPublicWhmcsUnsuspendRouteImport } from './routes/api/public/whmcs/unsuspend'
import { Route as ApiPublicWhmcsTerminateRouteImport } from './routes/api/public/whmcs/terminate'
import { Route as ApiPublicWhmcsSuspendRouteImport } from './routes/api/public/whmcs/suspend'
import { Route as ApiPublicWhmcsProvisionRouteImport } from './routes/api/public/whmcs/provision'
import { Route as ApiPublicPluginUpdateCheckRouteImport } from './routes/api/public/plugin/update-check'
import { Route as ApiPublicPluginStatsRouteImport } from './routes/api/public/plugin/stats'
import { Route as ApiPublicPluginSendRouteImport } from './routes/api/public/plugin/send'
import { Route as ApiPublicPluginSelectDeviceRouteImport } from './routes/api/public/plugin/select-device'
import { Route as ApiPublicPluginHeartbeatRouteImport } from './routes/api/public/plugin/heartbeat'
import { Route as ApiPublicPluginDevicesRouteImport } from './routes/api/public/plugin/devices'
import { Route as ApiPublicPluginActivateRouteImport } from './routes/api/public/plugin/activate'
import { Route as ApiPublicCronTickRouteImport } from './routes/api/public/cron/tick'
import { Route as ApiPublicCronDailyReportRouteImport } from './routes/api/public/cron/daily-report'

const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSendRoute = AuthenticatedSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMembersRoute = AuthenticatedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLicensesRoute = AuthenticatedLicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroupsRoute = AuthenticatedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevicesRoute = AuthenticatedDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeviceRequestsRoute =
  AuthenticatedDeviceRequestsRouteImport.update({
    id: '/device-requests',
    path: '/device-requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCampaignsRoute = AuthenticatedCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBrandsRoute = AuthenticatedBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBlockedRoute = AuthenticatedBlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicWhmcsUpdateRoute = ApiPublicWhmcsUpdateRouteImport.update({
  id: '/api/public/whmcs/update',
  path: '/api/public/whmcs/update',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhmcsUnsuspendRoute = ApiPublicWhmcsUnsuspendRouteImport.update({
  id: '/api/public/whmcs/unsuspend',
  path: '/api/public/whmcs/unsuspend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhmcsTerminateRoute = ApiPublicWhmcsTerminateRouteImport.update({
  id: '/api/public/whmcs/terminate',
  path: '/api/public/whmcs/terminate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhmcsSuspendRoute = ApiPublicWhmcsSuspendRouteImport.update({
  id: '/api/public/whmcs/suspend',
  path: '/api/public/whmcs/suspend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhmcsProvisionRoute = ApiPublicWhmcsProvisionRouteImport.update({
  id: '/api/public/whmcs/provision',
  path: '/api/public/whmcs/provision',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPluginUpdateCheckRoute =
  ApiPublicPluginUpdateCheckRouteImport.update({
    id: '/api/public/plugin/update-check',
    path: '/api/public/plugin/update-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPluginStatsRoute = ApiPublicPluginStatsRouteImport.update({
  id: '/api/public/plugin/stats',
  path: '/api/public/plugin/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPluginSendRoute = ApiPublicPluginSendRouteImport.update({
  id: '/api/public/plugin/send',
  path: '/api/public/plugin/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPluginSelectDeviceRoute =
  ApiPublicPluginSelectDeviceRouteImport.update({
    id: '/api/public/plugin/select-device',
    path: '/api/public/plugin/select-device',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPluginHeartbeatRoute =
  ApiPublicPluginHeartbeatRouteImport.update({
    id: '/api/public/plugin/heartbeat',
    path: '/api/public/plugin/heartbeat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPluginDevicesRoute = ApiPublicPluginDevicesRouteImport.update({
  id: '/api/public/plugin/devices',
  path: '/api/public/plugin/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPluginActivateRoute = ApiPublicPluginActivateRouteImport.update({
  id: '/api/public/plugin/activate',
  path: '/api/public/plugin/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronTickRoute = ApiPublicCronTickRouteImport.update({
  id: '/api/public/cron/tick',
  path: '/api/public/cron/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronDailyReportRoute =
  ApiPublicCronDailyReportRouteImport.update({
    id: '/api/public/cron/daily-report',
    path: '/api/public/cron/daily-report',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/order': typeof OrderRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/blocked': typeof AuthenticatedBlockedRoute
  '/brands': typeof AuthenticatedBrandsRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/device-requests': typeof AuthenticatedDeviceRequestsRoute
  '/devices': typeof AuthenticatedDevicesRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/licenses': typeof AuthenticatedLicensesRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/members': typeof AuthenticatedMembersRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/send': typeof AuthenticatedSendRoute
  '/users': typeof AuthenticatedUsersRoute
  '/api/public/cron/daily-report': typeof ApiPublicCronDailyReportRoute
  '/api/public/cron/tick': typeof ApiPublicCronTickRoute
  '/api/public/plugin/activate': typeof ApiPublicPluginActivateRoute
  '/api/public/plugin/devices': typeof ApiPublicPluginDevicesRoute
  '/api/public/plugin/heartbeat': typeof ApiPublicPluginHeartbeatRoute
  '/api/public/plugin/select-device': typeof ApiPublicPluginSelectDeviceRoute
  '/api/public/plugin/send': typeof ApiPublicPluginSendRoute
  '/api/public/plugin/stats': typeof ApiPublicPluginStatsRoute
  '/api/public/plugin/update-check': typeof ApiPublicPluginUpdateCheckRoute
  '/api/public/whmcs/provision': typeof ApiPublicWhmcsProvisionRoute
  '/api/public/whmcs/suspend': typeof ApiPublicWhmcsSuspendRoute
  '/api/public/whmcs/terminate': typeof ApiPublicWhmcsTerminateRoute
  '/api/public/whmcs/unsuspend': typeof ApiPublicWhmcsUnsuspendRoute
  '/api/public/whmcs/update': typeof ApiPublicWhmcsUpdateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/order': typeof OrderRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/blocked': typeof AuthenticatedBlockedRoute
  '/brands': typeof AuthenticatedBrandsRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/device-requests': typeof AuthenticatedDeviceRequestsRoute
  '/devices': typeof AuthenticatedDevicesRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/licenses': typeof AuthenticatedLicensesRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/members': typeof AuthenticatedMembersRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/send': typeof AuthenticatedSendRoute
  '/users': typeof AuthenticatedUsersRoute
  '/api/public/cron/daily-report': typeof ApiPublicCronDailyReportRoute
  '/api/public/cron/tick': typeof ApiPublicCronTickRoute
  '/api/public/plugin/activate': typeof ApiPublicPluginActivateRoute
  '/api/public/plugin/devices': typeof ApiPublicPluginDevicesRoute
  '/api/public/plugin/heartbeat': typeof ApiPublicPluginHeartbeatRoute
  '/api/public/plugin/select-device': typeof ApiPublicPluginSelectDeviceRoute
  '/api/public/plugin/send': typeof ApiPublicPluginSendRoute
  '/api/public/plugin/stats': typeof ApiPublicPluginStatsRoute
  '/api/public/plugin/update-check': typeof ApiPublicPluginUpdateCheckRoute
  '/api/public/whmcs/provision': typeof ApiPublicWhmcsProvisionRoute
  '/api/public/whmcs/suspend': typeof ApiPublicWhmcsSuspendRoute
  '/api/public/whmcs/terminate': typeof ApiPublicWhmcsTerminateRoute
  '/api/public/whmcs/unsuspend': typeof ApiPublicWhmcsUnsuspendRoute
  '/api/public/whmcs/update': typeof ApiPublicWhmcsUpdateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/order': typeof OrderRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/blocked': typeof AuthenticatedBlockedRoute
  '/_authenticated/brands': typeof AuthenticatedBrandsRoute
  '/_authenticated/campaigns': typeof AuthenticatedCampaignsRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/device-requests': typeof AuthenticatedDeviceRequestsRoute
  '/_authenticated/devices': typeof AuthenticatedDevicesRoute
  '/_authenticated/groups': typeof AuthenticatedGroupsRoute
  '/_authenticated/licenses': typeof AuthenticatedLicensesRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/members': typeof AuthenticatedMembersRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/send': typeof AuthenticatedSendRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/api/public/cron/daily-report': typeof ApiPublicCronDailyReportRoute
  '/api/public/cron/tick': typeof ApiPublicCronTickRoute
  '/api/public/plugin/activate': typeof ApiPublicPluginActivateRoute
  '/api/public/plugin/devices': typeof ApiPublicPluginDevicesRoute
  '/api/public/plugin/heartbeat': typeof ApiPublicPluginHeartbeatRoute
  '/api/public/plugin/select-device': typeof ApiPublicPluginSelectDeviceRoute
  '/api/public/plugin/send': typeof ApiPublicPluginSendRoute
  '/api/public/plugin/stats': typeof ApiPublicPluginStatsRoute
  '/api/public/plugin/update-check': typeof ApiPublicPluginUpdateCheckRoute
  '/api/public/whmcs/provision': typeof ApiPublicWhmcsProvisionRoute
  '/api/public/whmcs/suspend': typeof ApiPublicWhmcsSuspendRoute
  '/api/public/whmcs/terminate': typeof ApiPublicWhmcsTerminateRoute
  '/api/public/whmcs/unsuspend': typeof ApiPublicWhmcsUnsuspendRoute
  '/api/public/whmcs/update': typeof ApiPublicWhmcsUpdateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/order'
    | '/activity'
    | '/billing'
    | '/blocked'
    | '/brands'
    | '/campaigns'
    | '/contacts'
    | '/dashboard'
    | '/device-requests'
    | '/devices'
    | '/groups'
    | '/licenses'
    | '/logs'
    | '/members'
    | '/orders'
    | '/reports'
    | '/send'
    | '/users'
    | '/api/public/cron/daily-report'
    | '/api/public/cron/tick'
    | '/api/public/plugin/activate'
    | '/api/public/plugin/devices'
    | '/api/public/plugin/heartbeat'
    | '/api/public/plugin/select-device'
    | '/api/public/plugin/send'
    | '/api/public/plugin/stats'
    | '/api/public/plugin/update-check'
    | '/api/public/whmcs/provision'
    | '/api/public/whmcs/suspend'
    | '/api/public/whmcs/terminate'
    | '/api/public/whmcs/unsuspend'
    | '/api/public/whmcs/update'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/order'
    | '/activity'
    | '/billing'
    | '/blocked'
    | '/brands'
    | '/campaigns'
    | '/contacts'
    | '/dashboard'
    | '/device-requests'
    | '/devices'
    | '/groups'
    | '/licenses'
    | '/logs'
    | '/members'
    | '/orders'
    | '/reports'
    | '/send'
    | '/users'
    | '/api/public/cron/daily-report'
    | '/api/public/cron/tick'
    | '/api/public/plugin/activate'
    | '/api/public/plugin/devices'
    | '/api/public/plugin/heartbeat'
    | '/api/public/plugin/select-device'
    | '/api/public/plugin/send'
    | '/api/public/plugin/stats'
    | '/api/public/plugin/update-check'
    | '/api/public/whmcs/provision'
    | '/api/public/whmcs/suspend'
    | '/api/public/whmcs/terminate'
    | '/api/public/whmcs/unsuspend'
    | '/api/public/whmcs/update'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/order'
    | '/_authenticated/activity'
    | '/_authenticated/billing'
    | '/_authenticated/blocked'
    | '/_authenticated/brands'
    | '/_authenticated/campaigns'
    | '/_authenticated/contacts'
    | '/_authenticated/dashboard'
    | '/_authenticated/device-requests'
    | '/_authenticated/devices'
    | '/_authenticated/groups'
    | '/_authenticated/licenses'
    | '/_authenticated/logs'
    | '/_authenticated/members'
    | '/_authenticated/orders'
    | '/_authenticated/reports'
    | '/_authenticated/send'
    | '/_authenticated/users'
    | '/api/public/cron/daily-report'
    | '/api/public/cron/tick'
    | '/api/public/plugin/activate'
    | '/api/public/plugin/devices'
    | '/api/public/plugin/heartbeat'
    | '/api/public/plugin/select-device'
    | '/api/public/plugin/send'
    | '/api/public/plugin/stats'
    | '/api/public/plugin/update-check'
    | '/api/public/whmcs/provision'
    | '/api/public/whmcs/suspend'
    | '/api/public/whmcs/terminate'
    | '/api/public/whmcs/unsuspend'
    | '/api/public/whmcs/update'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OrderRoute: typeof OrderRoute
  ApiPublicCronDailyReportRoute: typeof ApiPublicCronDailyReportRoute
  ApiPublicCronTickRoute: typeof ApiPublicCronTickRoute
  ApiPublicPluginActivateRoute: typeof ApiPublicPluginActivateRoute
  ApiPublicPluginDevicesRoute: typeof ApiPublicPluginDevicesRoute
  ApiPublicPluginHeartbeatRoute: typeof ApiPublicPluginHeartbeatRoute
  ApiPublicPluginSelectDeviceRoute: typeof ApiPublicPluginSelectDeviceRoute
  ApiPublicPluginSendRoute: typeof ApiPublicPluginSendRoute
  ApiPublicPluginStatsRoute: typeof ApiPublicPluginStatsRoute
  ApiPublicPluginUpdateCheckRoute: typeof ApiPublicPluginUpdateCheckRoute
  ApiPublicWhmcsProvisionRoute: typeof ApiPublicWhmcsProvisionRoute
  ApiPublicWhmcsSuspendRoute: typeof ApiPublicWhmcsSuspendRoute
  ApiPublicWhmcsTerminateRoute: typeof ApiPublicWhmcsTerminateRoute
  ApiPublicWhmcsUnsuspendRoute: typeof ApiPublicWhmcsUnsuspendRoute
  ApiPublicWhmcsUpdateRoute: typeof ApiPublicWhmcsUpdateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/send': {
      id: '/_authenticated/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof AuthenticatedSendRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members': {
      id: '/_authenticated/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthenticatedMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/licenses': {
      id: '/_authenticated/licenses'
      path: '/licenses'
      fullPath: '/licenses'
      preLoaderRoute: typeof AuthenticatedLicensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups': {
      id: '/_authenticated/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devices': {
      id: '/_authenticated/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AuthenticatedDevicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/device-requests': {
      id: '/_authenticated/device-requests'
      path: '/device-requests'
      fullPath: '/device-requests'
      preLoaderRoute: typeof AuthenticatedDeviceRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns': {
      id: '/_authenticated/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthenticatedCampaignsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brands': {
      id: '/_authenticated/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof AuthenticatedBrandsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/blocked': {
      id: '/_authenticated/blocked'
      path: '/blocked'
      fullPath: '/blocked'
      preLoaderRoute: typeof AuthenticatedBlockedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/whmcs/update': {
      id: '/api/public/whmcs/update'
      path: '/api/public/whmcs/update'
      fullPath: '/api/public/whmcs/update'
      preLoaderRoute: typeof ApiPublicWhmcsUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whmcs/unsuspend': {
      id: '/api/public/whmcs/unsuspend'
      path: '/api/public/whmcs/unsuspend'
      fullPath: '/api/public/whmcs/unsuspend'
      preLoaderRoute: typeof ApiPublicWhmcsUnsuspendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whmcs/terminate': {
      id: '/api/public/whmcs/terminate'
      path: '/api/public/whmcs/terminate'
      fullPath: '/api/public/whmcs/terminate'
      preLoaderRoute: typeof ApiPublicWhmcsTerminateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whmcs/suspend': {
      id: '/api/public/whmcs/suspend'
      path: '/api/public/whmcs/suspend'
      fullPath: '/api/public/whmcs/suspend'
      preLoaderRoute: typeof ApiPublicWhmcsSuspendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whmcs/provision': {
      id: '/api/public/whmcs/provision'
      path: '/api/public/whmcs/provision'
      fullPath: '/api/public/whmcs/provision'
      preLoaderRoute: typeof ApiPublicWhmcsProvisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/plugin/update-check': {
      id: '/api/public/plugin/update-check'
      path: '/api/public/plugin/update-check'
      fullPath: '/api/public/plugin/update-check'
      preLoaderRoute: typeof ApiPublicPluginUpdateCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/plugin/stats': {
      id: '/api/public/plugin/stats'
      path: '/api/public/plugin/stats'
      fullPath: '/api/public/plugin/stats'
      preLoaderRoute: typeof ApiPublicPluginStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/plugin/send': {
      id: '/api/public/plugin/send'
      path: '/api/public/plugin/send'
      fullPath: '/api/public/plugin/send'
      preLoaderRoute: typeof ApiPublicPluginSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/plugin/select-device': {
      id: '/api/public/plugin/select-device'
      path: '/api/public/plugin/select-device'
      fullPath: '/api/public/plugin/select-device'
      preLoaderRoute: typeof ApiPublicPluginSelectDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/plugin/heartbeat': {
      id: '/api/public/plugin/heartbeat'
      path: '/api/public/plugin/heartbeat'
      fullPath: '/api/public/plugin/heartbeat'
      preLoaderRoute: typeof ApiPublicPluginHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/plugin/devices': {
      id: '/api/public/plugin/devices'
      path: '/api/public/plugin/devices'
      fullPath: '/api/public/plugin/devices'
      preLoaderRoute: typeof ApiPublicPluginDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/plugin/activate': {
      id: '/api/public/plugin/activate'
      path: '/api/public/plugin/activate'
      fullPath: '/api/public/plugin/activate'
      preLoaderRoute: typeof ApiPublicPluginActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/tick': {
      id: '/api/public/cron/tick'
      path: '/api/public/cron/tick'
      fullPath: '/api/public/cron/tick'
      preLoaderRoute: typeof ApiPublicCronTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/daily-report': {
      id: '/api/public/cron/daily-report'
      path: '/api/public/cron/daily-report'
      fullPath: '/api/public/cron/daily-report'
      preLoaderRoute: typeof ApiPublicCronDailyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedBlockedRoute: typeof AuthenticatedBlockedRoute
  AuthenticatedBrandsRoute: typeof AuthenticatedBrandsRoute
  AuthenticatedCampaignsRoute: typeof AuthenticatedCampaignsRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDeviceRequestsRoute: typeof AuthenticatedDeviceRequestsRoute
  AuthenticatedDevicesRoute: typeof AuthenticatedDevicesRoute
  AuthenticatedGroupsRoute: typeof AuthenticatedGroupsRoute
  AuthenticatedLicensesRoute: typeof AuthenticatedLicensesRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedMembersRoute: typeof AuthenticatedMembersRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSendRoute: typeof AuthenticatedSendRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedBlockedRoute: AuthenticatedBlockedRoute,
  AuthenticatedBrandsRoute: AuthenticatedBrandsRoute,
  AuthenticatedCampaignsRoute: AuthenticatedCampaignsRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDeviceRequestsRoute: AuthenticatedDeviceRequestsRoute,
  AuthenticatedDevicesRoute: AuthenticatedDevicesRoute,
  AuthenticatedGroupsRoute: AuthenticatedGroupsRoute,
  AuthenticatedLicensesRoute: AuthenticatedLicensesRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedMembersRoute: AuthenticatedMembersRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSendRoute: AuthenticatedSendRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OrderRoute: OrderRoute,
  ApiPublicCronDailyReportRoute: ApiPublicCronDailyReportRoute,
  ApiPublicCronTickRoute: ApiPublicCronTickRoute,
  ApiPublicPluginActivateRoute: ApiPublicPluginActivateRoute,
  ApiPublicPluginDevicesRoute: ApiPublicPluginDevicesRoute,
  ApiPublicPluginHeartbeatRoute: ApiPublicPluginHeartbeatRoute,
  ApiPublicPluginSelectDeviceRoute: ApiPublicPluginSelectDeviceRoute,
  ApiPublicPluginSendRoute: ApiPublicPluginSendRoute,
  ApiPublicPluginStatsRoute: ApiPublicPluginStatsRoute,
  ApiPublicPluginUpdateCheckRoute: ApiPublicPluginUpdateCheckRoute,
  ApiPublicWhmcsProvisionRoute: ApiPublicWhmcsProvisionRoute,
  ApiPublicWhmcsSuspendRoute: ApiPublicWhmcsSuspendRoute,
  ApiPublicWhmcsTerminateRoute: ApiPublicWhmcsTerminateRoute,
  ApiPublicWhmcsUnsuspendRoute: ApiPublicWhmcsUnsuspendRoute,
  ApiPublicWhmcsUpdateRoute: ApiPublicWhmcsUpdateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
